//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModelDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stud
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public Nullable<int> Percentage { get; set; }
    }
}
